HomeWork_Lesson_5
Boginsky/TMS pull request #1
Opened 2021-02-01 08:16 UTC by Boginsky

2021-02-01 16:58 UTC, NataliaKrolikova approved these changes

2021-02-01 16:58 UTC, NataliaKrolikova commented on lesson5/src/Metoda_Java_Begginer/Task11.java
> +            System.out.println("Число непростое");
Работает верно, но можно написать намного короче. С одним if и for

2021-02-01 16:58 UTC, NataliaKrolikova commented on lesson5/src/Metoda_Java_Begginer/Task14.java
> +
Здесь не верно. Ты должен прописать так, чтобы при выводе чисел оно автоматом вычесляло какое место занимает число в массиве и исходя не из порядка от меньшего к большему, а исходя из места которое оно занимает при выводе. Допустим я задала числа 58, 3, 25, 7, 11. Получается 3 самая низкая оценка и занимает она позицию 1, 58 занимает позицию 0.

2021-02-06 15:16 UTC, RomanKashenok requested changes

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Metoda_Java_Begginer/Task14.java
> +        for (int num : array) {
you can made both operations in one cycle

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Metoda_Java_Begginer/Task14.java
> +        for (int i = 0; i < array.length; i++) {
you can make all 4 operations in one cycle :)

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Other/Task7.java
> +        System.out.println(summ);
почему не верна? все верно. Тут можно смотреть так:
1 + 99
3+97
5+95
7+93
9+91
сумма получается 500 и таких последовательностей - 5. Итого 5 * 500 = 2500

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Other/Task5.java
> +            System.out.println("САНТИМЕТРЫ:");
люто плюсую!!!

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Other/Task5.java
> +        float[][] array = new float[2][20];
array is unnecessary here

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Other/Task2.java
> +        int hour = in.nextInt();
what is the purpose of 'hour'? What if there will be 1,2,3 ?

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Metoda_Java_Begginer/Task16.java
> +        while (!isSorted) {
without sorting please

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Metoda_Java_Begginer/Task15.java
> +        boolean isSorted1 = false;
and here too

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Metoda_Java_Begginer/Task15.java
> +        boolean isSorted = false;
you don't need sorting here

2021-02-06 15:16 UTC, RomanKashenok commented on lesson5/src/Metoda_Java_Begginer/Task15.java
> +import org.w3c.dom.ls.LSOutput;
what is this?

2021-02-12 10:14 UTC, RomanKashenok requested changes

2021-02-12 10:14 UTC, RomanKashenok commented on lesson8/src/lesson8/Task19.java
> +        System.out.println("Количество слов равно: " + n );
не прокатит с предложением типа "в этом предложении,к примеру,семь слов".

2021-02-12 10:14 UTC, RomanKashenok commented on lesson8/src/lesson8/Task20.java
> +            if(symbol == ' '){
а если взять предложение из предыдущего комментария?

2021-02-12 10:14 UTC, RomanKashenok commented on lesson8/src/lesson8/Task21.java
> +public class Task21 {
И в целом осталось непонятно какой метод сколько времени занимает

2021-02-15 20:38 UTC, merged